services:
  - type: web
    name: developer-portfolio
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "6543"
      - key: DB_NAME
        value: "postgres"
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: BETTER_AUTH_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: "admin@developer.com"
      - key: ADMIN_PASSWORD
        sync: false
